#Archivo que sirve para levantar backend y base de datos en contenedores Docker
#Requiere inicializaci√≥n de Docker Desktop
services:
  mysql:
    image: mysql:8.0
    container_name: greenlab-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: greenlab
      MYSQL_USER: greenlab_user
      MYSQL_PASSWORD: greenlab_pass
      TZ: Europe/Madrid
    ports:
      - "3307:3306"
    volumes:
      - greenlab_db:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: greenlab-backend
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_DEBUG: "1"
      SECRET_KEY: dev-secret
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_NAME: greenlab
      DB_USER: root
      DB_PASSWORD: root1234
    ports:
      - "5000:5000"

volumes:
  greenlab_db:
